# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "DjakaWeb"

app_domain: "djaka.therabbit.it"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "djaka"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
      encoding:  'utf8'
      #start_tag: '[%'
      #end_tag:   '%]'

log: 'debug'
startup_info: 1
show_errors:  1

session: YAML

plugins:
  DBIC:
    djaka:
      dsn: dbi:SQLite:dbname=/home/web/DjakaWeb/DB/djaka.db
      schema_class: DjakaWeb::DjakartaDB
      #user: root
      #pass: secret
      options:
        RaiseError: 1
        PrintError: 1

facebook:
    app_id: "289526111061581"
    graph_domain: "djakaweb"
    secret: "def970e709749e1864972bc65da425f9"
    graph_url: "http://graph.facebook.com/"



#paths
stories_path: /home/web/DjakaWeb/stories

#User defined variables
danger_threshold: 100
wait_to_click: 1
wait_to_support_click: 1

clicks:
    #common
    RESEARCH: 3
    #people and places
    SPY: 4
    #people
    KILL: 7
    TAKE: 7
    INTERROGATE: 5
    BRIBE: 5
    #places
    ASSAULT: 8
    INSPECT: 5
    INFILTRATE: 6
    VISIT: 3
    #objects
    PICKUP: 4
