INSERT INTO TEST_STATUS (STATUS_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (1, '0000', 1, 'ANGRY');
INSERT INTO TEST_STATUS (STATUS_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (1, '0001', 1, 'ANGRY');
INSERT INTO TEST_STATUS (STATUS_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (1, '0002', 1, '');
INSERT INTO TEST_STATUS (STATUS_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (2, '0000', 1, 'ANGRY');
INSERT INTO TEST_STATUS (STATUS_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (2, '0001', 1, '');
INSERT INTO TEST_STATUS (STATUS_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (2, '0002', 1, '');

