ALTER TABLE `CLICKS` ENGINE = InnoDB;
ALTER TABLE `GAMES` ENGINE = InnoDB;
ALTER TABLE `GAMES_STATUS` ENGINE = InnoDB;
ALTER TABLE `ONGOING_ACTIONS` ENGINE = InnoDB;
ALTER TABLE `STORIES` ENGINE = InnoDB;
ALTER TABLE `USERS` ENGINE = InnoDB;
