CREATE INDEX telling
ON STORIES (GAME_ID);

CREATE INDEX what_action
ON STORIES (PARENT_ACTION);

ALTER TABLE `STORIES` 
ADD FOREIGN KEY ( `GAME_ID` ) 
REFERENCES `djakarta`.`GAMES` (`ID` );

ALTER TABLE `STORIES` 
ADD FOREIGN KEY ( `PARENT_ACTION` ) 
REFERENCES `djakarta`.`ONGOING_ACTIONS` (`ID` );
