SELECT * FROM TEST_STATUS
WHERE STATUS_ID IN (SELECT STATUS_ID FROM TEST_STATUS
					WHERE OBJECT_CODE = '003' 
					AND STATUS = 'DEAD')
				AND
	  STATUS_ID IN (SELECT STATUS_ID FROM TEST_STATUS
					WHERE OBJECT_CODE = '005' 
					AND STATUS = 'DEAD');
