INSERT INTO GAMES_STATUS (GAME_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (1, '0000', 1, 'ANGRY');
INSERT INTO GAMES_STATUS (GAME_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (1, '0001', 1, 'ANGRY');
INSERT INTO GAMES_STATUS (GAME_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (1, '0002', 1, '');
INSERT INTO GAMES_STATUS (GAME_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (2, '0000', 1, 'ANGRY');
INSERT INTO GAMES_STATUS (GAME_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (2, '0001', 1, '');
INSERT INTO GAMES_STATUS (GAME_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (2, '0002', 1, '');
INSERT INTO GAMES_STATUS (GAME_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (3, '0000', 1, 'FRIEND');
INSERT INTO GAMES_STATUS (GAME_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (3, '0001', 1, 'FRIEND');
INSERT INTO GAMES_STATUS (GAME_ID, OBJECT_CODE, ACTIVE, STATUS)
VALUES (3, '0002', 1, 'FRIEND');

